version: '3.0'

services:
    hubble-app:
        image: "${HUBBLE_BACKEND_API_NAME}"
        container_name: "${HUBBLE_BACKEND_API}"
        ports:
            - "${HUBBLE_BACKEND_API_PORT}"
        hostname: hubble
        depends_on:
            - mongodb:mongo
        networks:
            - hubble

    mongodb:
        image: mongo:latest
        container_name: "${HUBBLE_MONGODB}"
        ports:
            - 27017
        hostname: mongodb
        volumes:
            - "${HUBBLE_MONGODB_VOL}"
        networks:
            - hubble

    hubble-taskrunner:
        image: "${HUBBLE_TASKRUNNER_NAME}"
        container_name: "${HUBBLE_TASKRUNNER}"
        hostname: hubble-taskrunner
        stdin_open: true
        tty: true
        depends_on:
            - mongodb:mongo
        networks:
            - hubble

networks:
    hubble:


