version: '3.0'

services:
<<<<<<< HEAD
    hubble-taskrunner:
            build: ./hubble.backend.tasksrunner
            container_name: "hubble-taskrunner"
            hostname: hubble-taskrunner
            stdin_open: true
            tty: true
            links:
                - mongodb:mongo
            
=======
    hubble-app:
        image: "${HUBBLE_BACKEND_API_NAME}"
        container_name: "${HUBBLE_BACKEND_API}"
        ports:
            - "${HUBBLE_BACKEND_API_PORT}"
        hostname: hubble
        depends_on:
            - mongodb:mongo
        networks:
            - hubble

>>>>>>> 8e545e0011cc13b8d8e01f938b22c804f22d8e7c
    mongodb:
        image: mongo:latest
        container_name: "hubble-mongodb"
        ports:
            - "27017:27017"
        hostname: mongodb
        volumes:
<<<<<<< HEAD
            - "/data/db"
    
    hubble-api:
        build: ./hubble.backend.api
        container_name: "hubble-backend"
        ports:
            - "8080:8080"
        hostname: hubble-api
        links:
=======
            - "${HUBBLE_MONGODB_VOL}"
        networks:
            - hubble

    hubble-taskrunner:
        image: "${HUBBLE_TASKRUNNER_NAME}"
        container_name: "${HUBBLE_TASKRUNNER}"
        hostname: hubble-taskrunner
        stdin_open: true
        tty: true
        depends_on:
>>>>>>> 8e545e0011cc13b8d8e01f938b22c804f22d8e7c
            - mongodb:mongo
        networks:
            - hubble

networks:
    hubble:

